repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.292"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.2.0"
    hooks:
      - id: pyproject-fmt
        args: [--indent, "4"]
